# Capstone 2: Business Analysis with Python
## Sales Territory Analysis
This project analyzes sales performance, customer activity, and product trends for Emporium.
The analysis compares sales performance between Florida and Texas within the South reigon.

In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [54]:
products = pd.read_csv('/content/Products.csv')
products.info()
products.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 669 entries, 0 to 668
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Prod Num       669 non-null    object
 1   Product        669 non-null    object
 2   CategoryID     669 non-null    int64
 3   SubcategoryID  669 non-null    object
dtypes: int64(1), object(3)
memory usage: 21.0+ KB

    Prod Num                        Product  CategoryID SubcategoryID
0  105248-IT               TCL NXTPAPER 10s         120       120-tab
1  105249-IT  Dell Latitude 7320 Detachable         120       120-tab
2  105250-IT                     Realme Pad         120       120-tab
3  105251-IT             Lenovo Tab P12 Pro         120       120-tab
4  105252-IT        Microsoft Surface Pro 9         120       120-tab

In [55]:
product_categories = pd.read_csv('/content/ProductCategories.csv')
product_categories.info()
product_categories.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CategoryID     52 non-null     int64
 1   Category       52 non-null     object
 2   SubcategoryID  52 non-null     object
 3   Subcategory    52 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.8+ KB

   CategoryID                  Category SubcategoryID           Subcategory
0         120  Technology & Accessories       120-tab               Tablets
1         120  Technology & Accessories       120-cal           Calculators
2         120  Technology & Accessories       120-sof     Software Download
3         120  Technology & Accessories       120-hea            Headphones
4         120  Technology & Accessories       120-ext  External Accessories

In [56]:
store_detail = pd.read_csv('/content/StoreDetail.csv')
store_detail.info()
store_detail.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Store Location     111 non-null    object
 1   State              111 non-null    object
 2   Store ID           111 non-null    int64
 3   Territory Manager  111 non-null    object
 4   Region             111 non-null    object
 5   Region Director    111 non-null    object
dtypes: int64(1), object(5)
memory usage: 5.3+ KB

  Store Location     State  Store ID Territory Manager Region  Region Director
0         Aurora  Colorado       701          Jim Heck   West  Cassie Chambers
1       Berthoud  Colorado       702          Jim Heck   West  Cassie Chambers
2        Boulder  Colorado       703          Jim Heck   West  Cassie Chambers
3    Castle Rock  Colorado       704          Jim Heck   West  Cassie Chambers
4         Denver  Colorado       705          Jim Heck   West  Cassie Chambers

In [57]:
store_sales = pd.read_csv('/content/StoreSales.csv')
store_sales.info()
store_sales.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335129 entries, 0 to 335128
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction Date  335129 non-null  object
 1   Store ID          335129 non-null  int64
 2   RewardsID         34943 non-null   float64
 3   Prod Num          335129 non-null  object
 4   Sale Amount       335129 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 12.8+ MB

  Transaction Date  Store ID  RewardsID  Prod Num  Sale Amount
0         1/1/2022       702        NaN  105349-M         8.00
1         1/1/2022       704        NaN  105350-T       144.00
2         1/1/2022       705        NaN  105351-M        44.00
3         1/1/2022       705        NaN  105352-M        47.61
4         1/1/2022       705        NaN  105353-A        20.36

In [58]:
customer_list = pd.read_csv('/content/customer_list.csv', sep='|')
customer_list.info()
customer_list.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cust_id       521 non-null    int64
 1   date          521 non-null    object
 2   time          521 non-null    object
 3   name          521 non-null    object
 4   email         521 non-null    object
 5   phone         520 non-null    object
 6   sms-opt-out   520 non-null    object
dtypes: int64(1), object(6)
memory usage: 28.6+ KB

,cust_id,date,time,name,email,phone,sms-opt-out
0,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N
1,2,2023-05-22,12:30:45,R. Geller,rossg@centralperk.coffee,212-555-1002,N
2,3,2023-07-09,18:15:27,Monica Geller,chefmonica@centralperk.coffee,212-555-1003,N
3,4,2023-09-01,21:05:33,Chandler Bing,chandlerb@centralperk.coffee,212-555-1004,Y
4,5,2023-11-18,14:22:10,Joey,howyoudoing@centralperk.coffee,212-555-1005,N

# Core Marketing Analysis

## Territory Managers and Store Location

In [71]:
south_region = store_detail[store_detail['Region'] == 'South']

south_region[['Store ID', 'Store Location', 'State', 'Territory Manager']]

     Store ID   Store Location           State      Territory Manager
26        719   Cape Canaveral         Florida             Lana Ilana
27        720  Fort Lauderdale         Florida             Lana Ilana
28        721     Jacksonville         Florida             Lana Ilana
29        722         Key West         Florida             Lana Ilana
30        723         Lakeland         Florida             Lana Ilana
31        724            Miami         Florida             Lana Ilana
32        725           Naples         Florida             Lana Ilana
33        726          Orlando         Florida             Lana Ilana
34        727          Sebring         Florida             Lana Ilana
35        728      Tallahassee         Florida             Lana Ilana
36        729            Tampa         Florida             Lana Ilana
98        852       Charleston  South Carolina             Len Jensen
99        853       Greenville  South Carolina             Len Jensen
100       901        Arlington           Texas  Jeff "Howdy" Richards
101       902           Austin           Texas  Jeff "Howdy" Richards
102       903          Bacliff           Texas  Jeff "Howdy" Richards
103       904          Baytown           Texas  Jeff "Howdy" Richards
104       905         Beaumont           Texas  Jeff "Howdy" Richards
105       906       Cedar Park           Texas  Jeff "Howdy" Richards
106       907           Dallas           Texas  Jeff "Howdy" Richards
107       908           Denton           Texas  Jeff "Howdy" Richards
108       909           Desoto           Texas  Jeff "Howdy" Richards
109       910       Fort Worth           Texas  Jeff "Howdy" Richards
110       911       Georgetown           Texas  Jeff "Howdy" Richards

## Monthly Revenue

In [74]:
sales_detail = pd.merge(
    store_sales,
    store_detail,
    on='Store ID')

south_states = ['Texas', 'Florida']
sales_detail = sales_detail[sales_detail['State'].isin(south_states)]
sales_detail

,Transaction Date,Store ID,RewardsID,Prod Num,Sale Amount,Month,Store Location,State,Territory Manager,Region,Region Director
23,2022-01-01,719,NaN,105376-M,44.50,2022-01,Cape Canaveral,Florida,Lana Ilana,South,Andy Gisselquist
24,2022-01-01,721,NaN,105310-IT,71.74,2022-01,Jacksonville,Florida,Lana Ilana,South,Andy Gisselquist
25,2022-01-01,723,NaN,105377-A,5.00,2022-01,Lakeland,Florida,Lana Ilana,South,Andy Gisselquist
26,2022-01-01,723,NaN,105378-T,155.60,2022-01,Lakeland,Florida,Lana Ilana,South,Andy Gisselquist
27,2022-01-01,724,NaN,105379-A,28.00,2022-01,Miami,Florida,Lana Ilana,South,Andy Gisselquist
...,...,...,...,...,...,...,...,...,...,...,...
335124,2025-12-31,909,NaN,105353-A,20.36,2025-12,Desoto,Texas,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
335125,2025-12-31,909,332.0,105364-S,17.70,2025-12,Desoto,Texas,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
335126,2025-12-31,910,NaN,105672-B,26.52,2025-12,Fort Worth,Texas,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
335127,2025-12-31,910,NaN,105653-M,11.00,2025-12,Fort Worth,Texas,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
335128,2025-12-31,910,NaN,105300-IT,77.81,2025-12,Fort Worth,Texas,"Jeff ""Howdy"" Richards",South,Andy Gisselquist

In [75]:
store_sales['Transaction Date'] = pd.to_datetime(store_sales['Transaction Date'])
store_sales['Month'] = store_sales['Transaction Date'].dt.to_period('M')

monthly_revenue = sales_detail.groupby(['State', 'Month'])['Sale Amount'].sum() .reset_index()
monthly_revenue

      State    Month  Sale Amount
0   Florida  2022-01     48143.95
1   Florida  2022-02     46257.35
2   Florida  2022-03     53541.25
3   Florida  2022-04     49505.25
4   Florida  2022-05     58326.64
..      ...      ...          ...
91    Texas  2025-08     98630.93
92    Texas  2025-09    109065.94
93    Texas  2025-10    168955.72
94    Texas  2025-11    105400.74
95    Texas  2025-12     95570.59

[96 rows x 3 columns]

In [67]:
sales_detail = pd.merge(
    store_sales,
    store_detail,
    on='Store ID')
south_sales = sales_detail[sales_detail['Region'] == 'South']
south_sales_sorted = south_sales.sort_values(by='Sale Amount', ascending=False)
south_sales_sorted

,Transaction Date,Store ID,RewardsID,Prod Num,Sale Amount,Store Location,State,Territory Manager,Region,Region Director
311965,10/23/2025,729,NaN,105341-IT,1763.7,Tampa,Florida,Lana Ilana,South,Andy Gisselquist
39147,9/13/2022,909,NaN,105341-IT,1763.7,Desoto,Texas,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
74157,3/30/2023,726,NaN,105341-IT,1763.7,Orlando,Florida,Lana Ilana,South,Andy Gisselquist
224282,2/12/2025,901,NaN,105341-IT,1763.7,Arlington,Texas,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
293430,9/2/2025,723,NaN,105341-IT,1763.7,Lakeland,Florida,Lana Ilana,South,Andy Gisselquist
...,...,...,...,...,...,...,...,...,...,...
38829,9/11/2022,909,176.0,105821-S,2.4,Desoto,Texas,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
138261,1/24/2024,910,NaN,105821-S,2.4,Fort Worth,Texas,"Jeff ""Howdy"" Richards",South,Andy Gisselquist
99854,7/29/2023,722,NaN,105576-S,2.4,Key West,Florida,Lana Ilana,South,Andy Gisselquist
282110,7/26/2025,724,NaN,105402-S,2.4,Miami,Florida,Lana Ilana,South,Andy Gisselquist
230341,3/4/2025,728,NaN,105821-S,2.4,Tallahassee,Florida,Lana Ilana,South,Andy Gisselquist

In [76]:
customer_sales = pd.merge(customer_list,
                          store_sales,
                          left_on='cust_id',
                          right_on='RewardsID',
                          how='inner')
customer_sales

,cust_id,date,time,name,email,phone,sms-opt-out,Transaction Date,Store ID,RewardsID,Prod Num,Sale Amount,Month
0,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N,2022-01-11,835,1.0,105351-M,44.00,2022-01
1,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N,2022-06-04,806,1.0,105320-IT,30.16,2022-06
2,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N,2022-06-12,736,1.0,105741-B,17.70,2022-06
3,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N,2022-06-29,865,1.0,105902-T,134.56,2022-06
4,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N,2022-09-07,851,1.0,105460-IT,72.50,2022-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34938,521,2023-08-01,18:10:30,Linda Flynn-Fletcher,linda@danvillekids.com,555-555-3210,N,2025-09-02,828,521.0,105292-IT,113.82,2025-09
34939,521,2023-08-01,18:10:30,Linda Flynn-Fletcher,linda@danvillekids.com,555-555-3210,N,2025-09-22,728,521.0,105438-A,28.92,2025-09
34940,521,2023-08-01,18:10:30,Linda Flynn-Fletcher,linda@danvillekids.com,555-555-3210,N,2025-09-23,736,521.0,105618-M,27.61,2025-09
34941,521,2023-08-01,18:10:30,Linda Flynn-Fletcher,linda@danvillekids.com,555-555-3210,N,2025-11-26,834,521.0,105405-M,61.14,2025-11
34942,521,2023-08-01,18:10:30,Linda Flynn-Fletcher,linda@danvillekids.com,555-555-3210,N,2025-12-16,717,521.0,105289-IT,119.28,2025-12